### ISSUE TITLE
method does not override or implement a method from supertype error

### ISSUE THREAD

**Issue by hewrin** [januslo/react-native-sunmi-inner-scanner#10]
Hi, I am trying your example in the repo, and I get this error 

`method does not override or implement a method from supertype`

The error happens in `node_modules/react-native-sunmi-inner-scanner/android/src/main/java/com/sunmi/scanner/SunmiInnerScannerPackage.java`

I am using a detached version of Expo SDK 29 (React Native 0.55.4)

Thank you for your help

**Comment by januslo** [comment]
Hi, I just update and fixed the issue. plz see the last version code and my last release 
https://www.npmjs.com/package/react-native-sunmi-inner-scanner

**Comment by hewrin** [comment]
Yes it works now,  thank you very much :D
