### ISSUE TITLE
编译出现错误

### ISSUE THREAD

**Issue by hllhui** [januslo/react-native-sunmi-inner-scanner#3]
/node_modules/react-native-sunmi-inner-scanner/android/src/main/java/com/sunmi/scanner/SunmiInnerScannerPackage.java:16: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: ....../node_modules/react-native-sunmi-inner-scanner/android/src/main/java/com/sunmi/scanner/SunmiInnerScannerModule.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

我应该怎么解决？

**Comment by januslo** [comment]
那个版本？

**Comment by januslo** [comment]
我在 设置 编译版本的时候没有做好，但是你可以尝试使用一下版本
```shell
 compileSdkVersion 23
    buildToolsVersion "23.0.3"
```

**Comment by hllhui** [comment]
用这个出现问题
`compileSdkVersion 23
    buildToolsVersion "23.0.1"`

**Comment by januslo** [comment]
/node_modules/react-native-sunmi-inner-scanner/android/src/main/java/com/sunmi/scanner/SunmiInnerScannerPackage.java:16
这行是覆盖 react-native的方法的。请确认你已经安装好react-native的相关组件

**Comment by hllhui** [comment]
可能是我link 时错了，现在可以了

**Comment by januslo** [comment]
@hllhui fixed as well.Sorry about that.
