### ISSUE TITLE
Cannot read property 'oneOfType' of undefined

### ISSUE THREAD

**Issue by abrarmusa** [januslo/react-native-sunmi-inner-scanner#5]
Getting this error

```
Cannot read property 'oneOfType' of undefined
```

Please advise

**Comment by kenhuang** [comment]
I face the same issue, Update node_modules/react-native-sunmi-inner-scanner/index.js seems to fix the compile error.

```
import React,{Component} from 'react';// remove ,PropTypes
import PropTypes from 'prop-types'; //PropTypes
...
onCodeScan:PropTypes.func //change from React.PropTypes
```

**Comment by januslo** [comment]
I am going to test with the last EN version late on today. GMT+8

发自我的 iPhone

**Comment by januslo** [comment]
Close for no response for long time, cannot tell fixed or not.
